<?php
/**
 * Copyright © 2015 expertreccommerce. All rights reserved.
 */
?>
<?php
/**
 * {{controller}} {{action}} template
 *
 * @var $block \Expertrec\ExpertrecSiteSearch\Block\Adminhtml\Integration\StoreMid
 */
?>
<h1>Instructions for integrating Expertrec Site Search</h1>
Thanks for installing Expertrec Site Search for your Magento store.  Please follow <a href="https://blog.expertrec.com/magento2-plugin-installation">the instructions here.</a>